-- MPGS initial authoritative schema (M2).
-- Do not edit this file after release; add new migrations instead.

CREATE TABLE schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    applied_at_ms INTEGER NOT NULL
);

CREATE TABLE apps (
    app_id INTEGER PRIMARY KEY CHECK (app_id >= 0 AND app_id <= 4294967295),
    app_type TEXT NOT NULL CHECK (
        app_type IN (
            'game', 'demo', 'playtest', 'tool', 'dlc', 'application',
            'music', 'video', 'series', 'comic', 'advertising', 'mod',
            'hardware', 'unknown'
        )
    ),
    canonical_name TEXT NOT NULL,
    release_state TEXT NOT NULL CHECK (
        release_state IN (
            'released', 'upcoming', 'coming_soon', 'retired', 'unknown'
        )
    ),
    release_date TEXT,
    release_date_precision TEXT CHECK (
        release_date_precision IS NULL
        OR release_date_precision IN ('day', 'month', 'quarter', 'year', 'tba')
    ),
    is_early_access INTEGER CHECK (is_early_access IS NULL OR is_early_access IN (0, 1)),
    current_data_confidence REAL CHECK (
        current_data_confidence IS NULL
        OR (current_data_confidence >= 0 AND current_data_confidence <= 1)
    ),
    source_modified_at_ms INTEGER,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL
);

CREATE INDEX idx_apps_release ON apps (release_state, release_date);
CREATE INDEX idx_apps_type ON apps (app_type);
CREATE INDEX idx_apps_updated ON apps (updated_at_ms);

CREATE TABLE app_relations (
    source_app_id INTEGER NOT NULL REFERENCES apps (app_id),
    target_app_id INTEGER NOT NULL REFERENCES apps (app_id),
    relation_type TEXT NOT NULL CHECK (
        relation_type IN (
            'demo_of', 'playtest_of', 'dedicated_server_for', 'edition_of', 'replaces'
        )
    ),
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    evidence_id INTEGER,
    verified_by_human INTEGER NOT NULL DEFAULT 0 CHECK (verified_by_human IN (0, 1)),
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    PRIMARY KEY (source_app_id, target_app_id, relation_type)
);

CREATE TABLE app_localizations (
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    language TEXT NOT NULL,
    name TEXT,
    short_description TEXT,
    source TEXT NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    PRIMARY KEY (app_id, language)
);

CREATE TABLE multiplayer_profiles (
    app_id INTEGER PRIMARY KEY REFERENCES apps (app_id),
    dominant_mode TEXT,
    connection_methods_json TEXT,
    server_dependency TEXT,
    join_methods_json TEXT,
    progression_type TEXT,
    min_players INTEGER,
    recommended_min_players INTEGER,
    recommended_max_players INTEGER,
    hard_max_players INTEGER,
    private_session INTEGER CHECK (private_session IS NULL OR private_session IN (0, 1)),
    online_coop INTEGER CHECK (online_coop IS NULL OR online_coop IN (0, 1)),
    self_hosted_server INTEGER CHECK (self_hosted_server IS NULL OR self_hosted_server IN (0, 1)),
    drop_in_out INTEGER CHECK (drop_in_out IS NULL OR drop_in_out IN (0, 1)),
    crossplay INTEGER CHECK (crossplay IS NULL OR crossplay IN (0, 1)),
    service_status TEXT,
    profile_confidence REAL CHECK (
        profile_confidence IS NULL
        OR (profile_confidence >= 0 AND profile_confidence <= 1)
    ),
    computed_at_ms INTEGER NOT NULL,
    CHECK (
        recommended_min_players IS NULL
        OR recommended_max_players IS NULL
        OR recommended_min_players <= recommended_max_players
    )
);

CREATE TABLE feature_evidence (
    evidence_id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    feature_name TEXT NOT NULL,
    value_json TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    source_document_id INTEGER,
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    observed_at_ms INTEGER NOT NULL,
    expires_at_ms INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))
);

CREATE INDEX idx_feature_evidence_active
    ON feature_evidence (app_id, feature_name, is_active);

CREATE TABLE curation_overrides (
    override_id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    feature_name TEXT NOT NULL,
    value_json TEXT NOT NULL,
    reason TEXT NOT NULL,
    external_evidence TEXT,
    operator TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    revoked_at_ms INTEGER,
    revoked_by TEXT,
    revoke_reason TEXT
);

CREATE INDEX idx_curation_overrides_active
    ON curation_overrides (app_id, feature_name, revoked_at_ms);

CREATE TABLE review_snapshots (
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    region_scope TEXT NOT NULL DEFAULT 'all',
    language_scope TEXT NOT NULL,
    captured_at_ms INTEGER NOT NULL,
    total_positive INTEGER NOT NULL CHECK (total_positive >= 0),
    total_negative INTEGER NOT NULL CHECK (total_negative >= 0),
    total_reviews INTEGER NOT NULL CHECK (total_reviews >= 0),
    review_score INTEGER,
    review_score_desc TEXT,
    wilson_lower REAL,
    filter_offtopic_activity INTEGER NOT NULL CHECK (filter_offtopic_activity IN (0, 1)),
    parameter_hash TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    source TEXT NOT NULL,
    PRIMARY KEY (app_id, region_scope, language_scope, captured_at_ms)
);

CREATE TABLE player_snapshots (
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    captured_at_ms INTEGER NOT NULL,
    player_count INTEGER,
    result_code INTEGER NOT NULL,
    missing_reason TEXT,
    content_hash TEXT NOT NULL,
    source TEXT NOT NULL,
    offline_players_excluded INTEGER NOT NULL DEFAULT 1 CHECK (offline_players_excluded IN (0, 1)),
    PRIMARY KEY (app_id, captured_at_ms)
);

CREATE TABLE player_daily (
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    day_utc TEXT NOT NULL,
    min_ccu INTEGER,
    max_ccu INTEGER,
    mean_ccu REAL,
    median_approx_ccu REAL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    missing_rate REAL NOT NULL DEFAULT 0 CHECK (missing_rate >= 0 AND missing_rate <= 1),
    updated_at_ms INTEGER NOT NULL,
    PRIMARY KEY (app_id, day_utc)
);

CREATE TABLE price_snapshots (
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    country_code TEXT NOT NULL,
    currency TEXT NOT NULL,
    captured_at_ms INTEGER NOT NULL,
    initial_price_minor INTEGER,
    final_price_minor INTEGER,
    discount_percent INTEGER,
    is_purchasable INTEGER CHECK (is_purchasable IS NULL OR is_purchasable IN (0, 1)),
    package_id TEXT,
    source TEXT NOT NULL,
    PRIMARY KEY (app_id, country_code, currency, captured_at_ms)
);

CREATE TABLE release_events (
    event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_id INTEGER NOT NULL REFERENCES apps (app_id),
    old_release_date TEXT,
    new_release_date TEXT,
    old_precision TEXT,
    new_precision TEXT,
    old_release_state TEXT,
    new_release_state TEXT,
    source TEXT NOT NULL,
    observed_at_ms INTEGER NOT NULL
);

CREATE TABLE source_documents (
    document_id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    content_type TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    content_text TEXT,
    fetched_at_ms INTEGER NOT NULL,
    expires_at_ms INTEGER,
    parse_version TEXT NOT NULL
);

CREATE INDEX idx_source_documents_entity
    ON source_documents (source, entity_type, entity_key, fetched_at_ms);

CREATE TABLE source_cursors (
    cursor_key TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    cursor_json TEXT NOT NULL,
    etag TEXT,
    last_success_at_ms INTEGER,
    next_run_at_ms INTEGER,
    updated_at_ms INTEGER NOT NULL
);

CREATE TABLE source_runs (
    run_id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    task_type TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'succeeded', 'failed', 'partial')
    ),
    started_at_ms INTEGER NOT NULL,
    finished_at_ms INTEGER,
    request_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    error_category TEXT,
    rate_limit_hits INTEGER NOT NULL DEFAULT 0,
    parser_version TEXT NOT NULL,
    notes TEXT
);

CREATE TABLE jobs (
    job_id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    task_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    due_at_ms INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('pending', 'leased', 'completed', 'failed', 'dead')
    ),
    lease_owner TEXT,
    lease_expires_at_ms INTEGER,
    idempotency_key TEXT NOT NULL UNIQUE,
    payload_json TEXT,
    last_error_category TEXT,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL
);

CREATE INDEX idx_jobs_lease
    ON jobs (status, due_at_ms, priority);

CREATE INDEX idx_jobs_entity
    ON jobs (source, task_type, entity_key);

CREATE TABLE audit_events (
    audit_id INTEGER PRIMARY KEY AUTOINCREMENT,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    before_json TEXT,
    after_json TEXT,
    reason TEXT,
    request_id TEXT,
    created_at_ms INTEGER NOT NULL
);

CREATE INDEX idx_audit_events_entity
    ON audit_events (entity_type, entity_key, created_at_ms);
